# src/cf/HistoryBundle/Resources/config/services.yml
parameters:
#     usuario.example.class: Cupon\UsuarioBundle\Example
services:
#    cf.historylogbundle.listener.request:
#        class: cf\HistoryLogBundle\Listener\RequestListener
#        tags:
#            - { name: kernel.event_listener, event: security.interactive_login }
#            - { name: kernel.event_listener, event: kernel.request }

    cf.historylogbundle.listener.history:
        class: Cf\HistoryLogBundle\Listener\HistoryLogListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }

    cf.historylogbundle.search:
        class: Cf\HistoryLogBundle\Listener\SearchHistoryLogListener
        arguments: ['@service_container']